version: '3'
services:
  main:
    image: cjoakim/azure-blobs-core:latest
    environment:
    - RUNTYPE=logic_app_process_blob
    - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
    - SOURCE_BLOB_PATH=/simulations/benjamin_hebert_1582653235.csv
    - SOURCE_BLOB_NAME=benjamin_hebert_1582653235.csv
    - TARGET_BLOB_CONTAINER=processed
    - POPULATE_STORAGE_RANDOM_PCT=5
    - POPULATE_STORAGE_DELAY=3